import json, os

def ing(spec):
    out = []
    for t in spec:
        d = {"i": t[0], "ml": None, "a": None, "opt": None}
        if isinstance(t[1], (int, float)):
            d["ml"] = float(t[1])
        else:
            d["a"] = t[1]
        if len(t) > 2 and t[2]:
            d["opt"] = True
        out.append(d)
    return out

def c(name, cat, glass, method, garnish, tags, steps, ings):
    return {"name": name, "cat": cat, "glass": glass, "method": method, "garnish": garnish,
            "tags": tags, "steps": steps, "ing": ing(ings)}

TOP = "Üstünü tamamla"
ICE = "Bardak dolusu"
K = "Klasik Kokteyl"
A = "Alkolsüz Kokteyl"

data = [
c("Mojito", K, "Highball bardağı", "build", "Nane dalı ve lime dilimi", ["klasik"],
  ["Nane yapraklarını ve şekeri bardağa ekleyin.", "Lime suyunu ilave edin.",
   "Hafifçe ezin; nane yapraklarını parçalamamaya dikkat edin.", "Beyaz romu ve buzu ekleyin.",
   "Üstünü soda ile tamamlayın.", "Bardağın dibinden yukarı doğru hafifçe karıştırın.",
   "Nane dalı ve lime dilimi ile süsleyin."],
  [("white rum", 50), ("lime juice", 25), ("mint", "10 yaprak"), ("sugar", "2 çay kaşığı"),
   ("soda water", TOP), ("ice", ICE)]),
c("Margarita", K, "Margarita kadehi", "shake", "Lime dilimi ve tuz kenarı", ["klasik"],
  ["Kadehin kenarını lime ile ıslatıp tuza batırın.", "Tekila, triple sec ve lime suyunu buzla dolu bir shaker'a koyun.",
   "10-15 saniye güçlüce çalkalayın.", "Hazırladığınız kadehe süzün.", "Lime dilimi ile süsleyin."],
  [("tequila", 50), ("triple sec", 20), ("lime juice", 15), ("salt", "Bardak kenarı için", True)]),
c("Daiquiri", K, "Coupe kadehi", "shake", "Lime dilimi", ["klasik", "sour"],
  ["Kadehi buzla soğutun.", "Rom, lime suyu ve şeker şurubunu buzla dolu shaker'a koyun.",
   "İyice çalkalayın.", "Soğuttuğunuz kadehe süzün.", "Lime dilimi ile süsleyin."],
  [("white rum", 50), ("lime juice", 25), ("simple syrup", 15)]),
c("Moscow Mule", K, "Bakır kupa", "build", "Lime dilimi ve nane dalı", ["klasik", "highball"],
  ["Bakır kupayı buzla doldurun.", "Votka ve lime suyunu ekleyin.", "Üstünü ginger beer ile tamamlayın.",
   "Hafifçe karıştırın.", "Lime dilimi ve nane dalı ile süsleyin."],
  [("vodka", 50), ("lime juice", 15), ("ginger beer", 100)]),
c("Cosmopolitan", K, "Martini kadehi", "shake", "Portakal kabuğu", ["klasik", "martini"],
  ["Tüm malzemeleri buzla dolu shaker'a koyun.", "İyice çalkalayın.", "Soğutulmuş martini kadehine süzün.",
   "Portakal kabuğu ile süsleyin."],
  [("vodka", 40), ("triple sec", 15), ("lime juice", 15), ("cranberry juice", 30)]),
c("Long Island Iced Tea", K, "Highball bardağı", "build", "Limon dilimi", ["klasik", "highball"],
  ["Highball bardağını buzla doldurun.", "Votka, cin, rom, tekila, triple sec, limon suyu ve şeker şurubunu ekleyin.",
   "Üstünü kola ile tamamlayın.", "Hafifçe karıştırın.", "Limon dilimi ile süsleyin."],
  [("vodka", 15), ("gin", 15), ("white rum", 15), ("tequila", 15), ("triple sec", 15),
   ("lemon juice", 25), ("simple syrup", 30), ("cola", TOP), ("ice", ICE)]),
c("Piña Colada", K, "Hurricane bardağı", "blend", "Ananas dilimi ve kokteyl kirazı", ["klasik", "tiki", "tropikal", "frozen"],
  ["Rom, hindistan cevizi kreması, ananas suyu ve bir su bardağı buzu blendera koyun.", "Pürüzsüz olana kadar karıştırın.",
   "Soğutulmuş hurricane bardağına dökün.", "Ananas dilimi ve kirazla süsleyin."],
  [("white rum", 50), ("cream of coconut", 30), ("pineapple juice", 50), ("ice", "1 su bardağı"),
   ("pineapple", "1 dilim", True), ("maraschino cherry", "1 adet", True)]),
c("Sex on the Beach", K, "Highball bardağı", "build", "Portakal dilimi", ["klasik", "highball"],
  ["Highball bardağını buzla doldurun.", "Votka ve şeftali likörünü ekleyin.",
   "Portakal suyu ve cranberry suyunu ilave edin.", "Hafifçe karıştırın.", "Portakal dilimi ile süsleyin."],
  [("vodka", 40), ("peach schnapps", 20), ("orange juice", 40), ("cranberry juice", 40), ("ice", ICE)]),
c("Old Fashioned", K, "Old Fashioned bardağı", "stir", "Portakal kabuğu", ["klasik"],
  ["Küp şekeri bardağa koyun; bitter ve birkaç damla su ekleyin.", "Şekeri eriyene kadar ezin.",
   "Bardağı buzla doldurun ve burbonu ekleyin.", "Yaklaşık 30 saniye karıştırın.",
   "Portakal kabuğunun yağını bardağın üzerine sıkın ve kabuğu bardağa bırakın."],
  [("bourbon", 50), ("sugar cube", "1 adet"), ("angostura bitters", "2 dash"), ("water", "Birkaç damla")]),
c("Negroni", K, "Old Fashioned bardağı", "stir", "Portakal dilimi", ["klasik"],
  ["Tüm malzemeleri buz dolu karıştırma bardağına koyun.", "20-30 saniye karıştırın.",
   "Buzla dolu Old Fashioned bardağına süzün.", "Portakal dilimi ile süsleyin."],
  [("gin", 30), ("campari", 30), ("sweet vermouth", 30)]),
c("Martini", K, "Martini kadehi", "stir", "Zeytin veya limon kabuğu", ["klasik", "martini"],
  ["Martini kadehini buzla soğutun.", "Cin ve kuru vermutu buz dolu karıştırma bardağına koyun.",
   "Yaklaşık 30 saniye karıştırın.", "Soğuttuğunuz kadehe süzün.", "Zeytin veya limon kabuğu ile süsleyin."],
  [("gin", 60), ("dry vermouth", 10)]),
c("Whiskey Sour", K, "Old Fashioned bardağı", "dryshake", "Kokteyl kirazı ve portakal dilimi", ["klasik", "sour"],
  ["Burbon, limon suyu, şeker şurubu ve yumurta akını buzsuz shaker'a koyun.", "Köpürene kadar buzsuz çalkalayın (dry shake).",
   "Buz ekleyip tekrar çalkalayın.", "Buzla dolu Old Fashioned bardağına süzün.", "Kiraz ve portakal dilimi ile süsleyin."],
  [("bourbon", 45), ("lemon juice", 25), ("simple syrup", 20), ("egg white", "1 adet", True)]),
c("Tequila Sunrise", K, "Highball bardağı", "build", "Portakal dilimi ve kiraz", ["klasik", "highball"],
  ["Highball bardağını buzla doldurun.", "Tekila ve portakal suyunu ekleyin, karıştırın.",
   "Grenadini yavaşça bardağın kenarından dökün; dibe çökecektir.", "Portakal dilimi ve kirazla süsleyin."],
  [("tequila", 50), ("orange juice", 100), ("grenadine", 15)]),
c("Aperol Spritz", K, "Şarap kadehi", "build", "Portakal dilimi", ["klasik"],
  ["Şarap kadehini buzla doldurun.", "Önce prosecco, sonra Aperol'ü ekleyin.", "Soda ile tamamlayın.",
   "Hafifçe karıştırın.", "Portakal dilimi ile süsleyin."],
  [("prosecco", 90), ("aperol", 60), ("soda water", 30)]),
c("Caipirinha", K, "Old Fashioned bardağı", "muddle", "Lime dilimi", ["klasik"],
  ["Limeyi dörde bölüp bardağa koyun.", "Şekeri ekleyip limenin suyunu salacak şekilde ezin.",
   "Bardağı kırılmış buzla doldurun.", "Cachaça'yı ekleyin ve karıştırın."],
  [("cachaca", 50), ("lime", "1 adet"), ("sugar", "2 çay kaşığı"), ("ice", ICE)]),
c("Manhattan", K, "Martini kadehi", "stir", "Kokteyl kirazı", ["klasik", "martini"],
  ["Tüm malzemeleri buz dolu karıştırma bardağına koyun.", "30 saniye karıştırın.", "Soğutulmuş kadehe süzün.",
   "Kirazla süsleyin."],
  [("whiskey", 50), ("sweet vermouth", 20), ("angostura bitters", "2 dash")]),
c("Espresso Martini", K, "Martini kadehi", "shake", "3 kahve çekirdeği", ["klasik", "martini"],
  ["Tüm malzemeleri buzla dolu shaker'a koyun.", "Köpürene kadar güçlüce çalkalayın.",
   "Soğutulmuş kadehe ince süzgeçle süzün.", "Üzerine 3 kahve çekirdeği koyun."],
  [("vodka", 50), ("coffee liqueur", 20), ("espresso", 30), ("simple syrup", 10)]),
c("Gin and Tonic", K, "Highball bardağı", "build", "Lime dilimi", ["klasik", "highball"],
  ["Bardağı buzla doldurun.", "Cini ekleyin.", "Tonik ile tamamlayın.", "Hafifçe karıştırın.", "Lime dilimi ile süsleyin."],
  [("gin", 50), ("tonic water", 150)]),
c("Tom Collins", K, "Collins bardağı", "shake", "Limon dilimi ve kiraz", ["klasik", "highball", "sour"],
  ["Cin, limon suyu ve şeker şurubunu buzla dolu shaker'a koyun.", "Çalkalayın.", "Buzla dolu Collins bardağına süzün.",
   "Soda ile tamamlayın.", "Limon dilimi ve kirazla süsleyin."],
  [("gin", 45), ("lemon juice", 30), ("simple syrup", 15), ("soda water", TOP)]),
c("Bloody Mary", K, "Highball bardağı", "build", "Kereviz sapı", ["klasik", "highball"],
  ["Highball bardağını buzla doldurun.", "Votka, domates suyu ve limon suyunu ekleyin.",
   "Worcestershire, tabasco, tuz ve karabiberi ilave edin.", "Nazikçe karıştırın.", "Kereviz sapı ile süsleyin."],
  [("vodka", 45), ("tomato juice", 90), ("lemon juice", 15), ("worcestershire sauce", "2 dash"),
   ("tabasco sauce", "2 dash"), ("salt", "1 tutam", True), ("black pepper", "1 tutam", True), ("celery", "1 sap", True)]),
c("Mai Tai", K, "Old Fashioned bardağı", "shake", "Nane dalı ve lime dilimi", ["klasik", "tiki"],
  ["Tüm malzemeleri buzla dolu shaker'a koyun.", "İyice çalkalayın.", "Kırılmış buzla dolu bardağa süzün.",
   "Nane dalı ve lime ile süsleyin."],
  [("white rum", 40), ("dark rum", 20), ("triple sec", 15), ("orgeat syrup", 15), ("lime juice", 30)]),
c("Cuba Libre", K, "Highball bardağı", "build", "Lime dilimi", ["klasik", "highball"],
  ["Highball bardağını buzla doldurun.", "Rom ve lime suyunu ekleyin.", "Kola ile tamamlayın.", "Hafifçe karıştırın.",
   "Lime dilimi ile süsleyin."],
  [("white rum", 50), ("lime juice", 10), ("cola", 120)]),
c("Dark and Stormy", K, "Highball bardağı", "build", "Lime dilimi", ["klasik", "highball"],
  ["Bardağı buzla doldurun.", "Ginger beer'i ekleyin.", "Koyu romu üzerine yavaşça dökün.", "Lime suyu ekleyin ve lime dilimi ile süsleyin."],
  [("dark rum", 60), ("ginger beer", 100), ("lime juice", 10)]),
c("Mimosa", "Şampanyalı Kokteyl", "Şampanya flüt", "build", "Portakal kabuğu", ["klasik", "sampanya"],
  ["Flüt kadehe önce şampanyayı yavaşça doldurun.", "Soğuk portakal suyunu ekleyin.", "Karıştırmadan servis edin."],
  [("champagne", 75), ("orange juice", 75)]),
c("Bellini", "Şampanyalı Kokteyl", "Şampanya flüt", "build", None, ["klasik", "sampanya"],
  ["Şeftali püresini flüt kadehe koyun.", "Üzerine yavaşça prosecco ekleyin.", "Hafifçe karıştırın."],
  [("prosecco", 100), ("peach puree", 50)]),
c("Kamikaze", "Shot", "Shot bardağı", "shake", "Lime dilimi", ["shot"],
  ["Tüm malzemeleri buzla dolu shaker'a koyun.", "Çalkalayın.", "Shot bardaklarına süzün."],
  [("vodka", 30), ("triple sec", 30), ("lime juice", 30)]),
c("Gimlet", K, "Coupe kadehi", "shake", "Lime dilimi", ["klasik", "sour"],
  ["Cin, lime suyu ve şeker şurubunu buzla dolu shaker'a koyun.", "Çalkalayın.", "Soğutulmuş kadehe süzün.", "Lime dilimi ile süsleyin."],
  [("gin", 50), ("lime juice", 20), ("simple syrup", 15)]),
c("Paloma", K, "Highball bardağı", "build", "Greyfurt dilimi ve tuz kenarı", ["klasik", "highball"],
  ["Bardağın kenarını tuzla süsleyin (isteğe bağlı).", "Bardağı buzla doldurun.", "Tekila, greyfurt suyu ve lime suyunu ekleyin.",
   "Soda ile tamamlayın ve hafifçe karıştırın."],
  [("tequila", 50), ("grapefruit juice", 60), ("lime juice", 10), ("soda water", TOP), ("salt", "Bardak kenarı için", True)]),
c("Amaretto Sour", K, "Old Fashioned bardağı", "dryshake", "Kokteyl kirazı", ["sour"],
  ["Amaretto, limon suyu, şeker şurubu ve yumurta akını buzsuz shaker'a koyun.", "Buzsuz çalkalayın.", "Buz ekleyip tekrar çalkalayın.",
   "Buzla dolu bardağa süzün.", "Kirazla süsleyin."],
  [("amaretto", 45), ("lemon juice", 25), ("simple syrup", 10), ("egg white", "1 adet", True)]),
c("Sidecar", K, "Coupe kadehi", "shake", "Portakal kabuğu", ["klasik", "sour"],
  ["Tüm malzemeleri buzla dolu shaker'a koyun.", "İyice çalkalayın.", "Soğutulmuş kadehe süzün.", "Portakal kabuğu ile süsleyin."],
  [("cognac", 50), ("triple sec", 20), ("lemon juice", 20)]),
c("Mint Julep", K, "Julep kupası", "muddle", "Bol nane dalı", ["klasik"],
  ["Nane yapraklarını şeker şurubuyla kupanın içinde hafifçe ezin.", "Burbonu ekleyin.", "Kupayı kırılmış buzla doldurun ve karıştırın.",
   "Bol nane dalı ile süsleyin."],
  [("bourbon", 60), ("mint", "8 yaprak"), ("simple syrup", 10), ("ice", ICE)]),
c("White Russian", K, "Old Fashioned bardağı", "build", None, ["klasik"],
  ["Bardağı buzla doldurun.", "Votka ve kahve likörünü ekleyin.", "Üzerine kremayı yavaşça dökün.", "Servis ederken hafifçe karıştırın."],
  [("vodka", 50), ("coffee liqueur", 20), ("cream", 30)]),
c("Screwdriver", K, "Highball bardağı", "build", "Portakal dilimi", ["highball"],
  ["Highball bardağını buzla doldurun.", "Votka ve portakal suyunu ekleyin.", "Karıştırın.", "Portakal dilimi ile süsleyin."],
  [("vodka", 50), ("orange juice", 100)]),
# Alkolsüz
c("Virgin Mojito", A, "Highball bardağı", "build", "Nane dalı ve lime dilimi", ["alkolsuz"],
  ["Nane yapraklarını ve şekeri bardağa koyun.", "Lime suyunu ekleyip hafifçe ezin.", "Bardağı kırılmış buzla doldurun.",
   "Soda ile tamamlayın ve karıştırın.", "Nane dalı ve lime dilimi ile süsleyin."],
  [("lime juice", 25), ("mint", "10 yaprak"), ("sugar", "2 çay kaşığı"), ("soda water", TOP), ("ice", ICE)]),
c("Shirley Temple", A, "Highball bardağı", "build", "Kokteyl kirazı", ["alkolsuz", "highball"],
  ["Bardağı buzla doldurun.", "Grenadini ekleyin.", "Ginger ale ile tamamlayın ve hafifçe karıştırın.", "Kirazla süsleyin."],
  [("ginger ale", 150), ("grenadine", 15), ("maraschino cherry", "1 adet", True)]),
c("Virgin Piña Colada", A, "Hurricane bardağı", "blend", "Ananas dilimi", ["alkolsuz", "tropikal", "frozen"],
  ["Hindistan cevizi kreması, ananas suyu ve bir su bardağı buzu blendera koyun.", "Pürüzsüz olana kadar karıştırın.",
   "Hurricane bardağına dökün.", "Ananas dilimi ile süsleyin."],
  [("cream of coconut", 30), ("pineapple juice", 90), ("ice", "1 su bardağı"), ("pineapple", "1 dilim", True)]),
c("Cinderella", A, "Highball bardağı", "shake", "Portakal dilimi", ["alkolsuz", "tropikal"],
  ["Meyve sularını ve grenadini buzla dolu shaker'a koyun.", "Çalkalayın.", "Buzla dolu bardağa süzün.", "Soda ile tamamlayın."],
  [("orange juice", 40), ("pineapple juice", 40), ("lemon juice", 20), ("grenadine", 10), ("soda water", TOP)]),
c("Mint Lemonade", A, "Highball bardağı", "muddle", "Nane dalı ve limon dilimi", ["alkolsuz", "highball"],
  ["Nane yapraklarını şeker şurubuyla hafifçe ezin.", "Limon suyunu ekleyin.", "Bardağı buzla doldurun.", "Soda ile tamamlayıp karıştırın."],
  [("lemon juice", 40), ("mint", "8 yaprak"), ("simple syrup", 25), ("soda water", TOP), ("ice", ICE)]),
]

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "assets", "cocktails_seed.json"), "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=1)
print(len(data), "kokteyl yazıldı")
